export const characters = [
    {
        ID: 1,
        name: "Mario",
        speed: 4,
        handling: 3,
        power: 3,
        score: 0,
    },
    {
        ID: 2,
        name: "Luigi",
        speed: 3,
        handling: 4,
        power: 3,
        score: 0,
    },
    {
        ID: 3,
        name: "Peach",
        speed: 2,
        handling: 4,
        power: 4,
        score: 0,
    },
    {
        ID: 4,
        name: "Yoshi",
        speed: 3,
        handling: 5,
        power: 2,
        score: 0,
    },
    {
        ID: 5,
        name: "Bowser",
        speed: 3,
        handling: 2,
        power: 5,
        score: 0,
    },
    {
        ID: 6,
        name: "Donkey Kong",
        speed: 2,
        handling: 3,
        power: 5,
        score: 0,
    },
];