// Foram passadas para cá as rolagens de dados para simplificar a passagem desses dados sem recorrer a outras variáveis
// Também foi incluído um boolean para indicar o status de velocidade negativa dada pela banana durante confrontos

export const characters = [
    {
        ID: 1,
        name: "Mario",
        speed: 4,
        handling: 3,
        power: 3,
        score: 0,
        spin: false,
        diceroll: 0,
    },
    {
        ID: 2,
        name: "Luigi",
        speed: 3,
        handling: 4,
        power: 4,
        score: 0,
        spin: false,
        diceroll: 0,
    },
    {
        ID: 3,
        name: "Peach",
        speed: 3,
        handling: 4,
        power: 2,
        score: 0,
        spin: false,
        diceroll: 0,
    },
    {
        ID: 4,
        name: "Yoshi",
        speed: 2,
        handling: 4,
        power: 3,
        score: 0,
        spin: false,
        diceroll: 0,
    },
    {
        ID: 5,
        name: "Bowser",
        speed: 5,
        handling: 2,
        power: 5,
        score: 0,
        spin: false,
        diceroll: 0,
    },
    {
        ID: 6,
        name: "Donkey Kong",
        speed: 2,
        handling: 2,
        power: 5,
        score: 0,
        spin: false,
        diceroll: 0,
    },
];